spring:
  application:
    name: devkobe-hompage
  # ================================================
  # =            Default Profile (dev)             =
  # ================================================
  # H2 Database Settings
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:formate_sql: true
    defer-datasource-initialization: true

  # Logging Level
  logging:
    level:
      org:
        hibernate:
          SQL: debug

